language: ruby
rvm:
  - "1.9.3"

env:
  - DB=sqlite
  - DB=postgresql

script:
  - 'cp config/database.travis.yml config/database.yml'
  - "RAILS_ENV=test bundle exec rake --trace db:test:load"
  - "RAILS_ENV=test bundle exec rspec spec"